name: Deploy Web Component Sandbox

on:
  push:
    branches: [main]
    paths:
      - frontend/**
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: sandbox

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        name: Build Widgets
        with:
          node-version: "16.x"
      - run: |
          cd ui
          npm ci --force
          npm run build

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - id: "upload-folder"
        name: "Upload Files to Google Storage"
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "./ui/dist/"
          destination: "sb-${{ vars.GOOGLE_PROJECT_ID }}-webcomponent/ui"
          parent: false
